# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s-oduojurjio5KJohhgPFL9x7pkl68WM
"""

import pandas as pd

data = pd.read_csv("WHO COVID-19 cases.csv")

print("Ma'lumotlarning birinchi 5 qatori:")
print(data.head())

cases_by_country = data.groupby("Country").sum()["Cumulative_cases"]

print("\nHar bir davlat bo'yicha umumiy COVID-19 holatlari:")
print(cases_by_country)

country_filter = "Uzbekistan"
uzbekistan_data = data[data["Country"] == country_filter]

print(f"\n{country_filter} uchun ma'lumotlar:")
print(uzbekistan_data)

import matplotlib.pyplot as plt

top_10_countries = cases_by_country.sort_values(ascending=False).head(10)

plt.figure(figsize=(10, 6))
top_10_countries.plot(kind="bar", color="skyblue")
plt.title("Eng ko'p COVID-19 holatlari aniqlangan davlatlar", fontsize=16)
plt.xlabel("Davlat", fontsize=12)
plt.ylabel("Cumulative Cases", fontsize=12)
plt.xticks(rotation=45)
plt.show()